[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aio-pika>=9.5.7",
    "aiochannel>=1.3.0",
    "bson>=0.5.10",
    "fastapi>=0.116.1",
    "grpcio-tools==1.64.0",
    "motor>=3.7.1",
    "pydantic>=2.11.7",
    "uvicorn>=0.35.0",
    "watchfiles>=1.1.0",
]
